spring:
  application:
    name: sididoc
  profiles:
    active: homolog

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    jwt:
      secret: ${SECURITY_JWT_SECRET}
      expiration-millis: ${JWT_EXPIRATION:3600000}

cors:
  origin-patterns: ${FRONTEND_URL}

aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}

supabase:
  bucket:
    name: ${SUPABASE_BUCKET_NAME}
  project:
    url: ${SUPABASE_PROJECT_URL}

app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}

langchain4j:
  gemini:
    api-key: ${GEMINI_API_KEY}
    model-name: ${MODEL_EMBEDDING_NAME}
    chat-model-name: ${MODEL_CHAT_NAME}
  vector-store:
    table: embeddings
    dimension: 768